local prepare_stats_table = utils_ui.prepare_stats_table
utils_ui.prepare_stats_table = function()
	prepare_stats_table()
	utils_ui.stats_table["booster"]["eat_satiety"] = {
		index = 4,
		typ = "float",
		name = "ui_inv_satiety",
		icon_p = "ui_am_prop_satiety_restore_speed",
		icon_n = "ui_am_prop_satiety",
		track = false,
		magnitude = 4000,
		unit = "st_kcal",
		compare = false,
		sign = true,
		show_always = false
	}
end
